REM INSERTING into PFINNGIFTMASTER
Insert into PFINNGIFTMASTER (GIFTID,GIFTDESCRIPTION,GIFTNAME,GIFTPOINTS) values (1,'Gift Voucher worth Rs. 50','Gift1',50);
Insert into PFINNGIFTMASTER (GIFTID,GIFTDESCRIPTION,GIFTNAME,GIFTPOINTS) values (2,'Gift Voucher worth Rs. 100','Gift2',100);
Insert into PFINNGIFTMASTER (GIFTID,GIFTDESCRIPTION,GIFTNAME,GIFTPOINTS) values (3,'Gift Voucher worth Rs. 150','Gift3',150);
Insert into PFINNGIFTMASTER (GIFTID,GIFTDESCRIPTION,GIFTNAME,GIFTPOINTS) values (4,'Gift Voucher worth Rs. 200','Gift4',200);
