REM INSERTING into PFINNEVENTMASTER
Insert into PFINNEVENTMASTER (SERIAL,EVENTTYPE,RATING,REWARDPOINTS,EVENTFULLNAME) values (7,'NEWIDEA','SIMPLE',20,'New Idea');
Insert into PFINNEVENTMASTER (SERIAL,EVENTTYPE,RATING,REWARDPOINTS,EVENTFULLNAME) values (8,'NEWIDEA','MODERATE',30,'New Idea');
Insert into PFINNEVENTMASTER (SERIAL,EVENTTYPE,RATING,REWARDPOINTS,EVENTFULLNAME) values (9,'NEWIDEA','COMPLEX',100,'New Idea');
Insert into PFINNEVENTMASTER (SERIAL,EVENTTYPE,RATING,REWARDPOINTS,EVENTFULLNAME) values (1,'SUGGESTION','SIMPLE',10,'Suggestion');
Insert into PFINNEVENTMASTER (SERIAL,EVENTTYPE,RATING,REWARDPOINTS,EVENTFULLNAME) values (2,'SUGGESTION','MODERATE',20,'Suggestion');
Insert into PFINNEVENTMASTER (SERIAL,EVENTTYPE,RATING,REWARDPOINTS,EVENTFULLNAME) values (3,'SUGGESTION','COMPLEX',30,'Suggestion');
Insert into PFINNEVENTMASTER (SERIAL,EVENTTYPE,RATING,REWARDPOINTS,EVENTFULLNAME) values (4,'FEEDBACK','SIMPLE',10,'Feedback');
Insert into PFINNEVENTMASTER (SERIAL,EVENTTYPE,RATING,REWARDPOINTS,EVENTFULLNAME) values (5,'FEEDBACK','MODERATE',20,'Feedback');
Insert into PFINNEVENTMASTER (SERIAL,EVENTTYPE,RATING,REWARDPOINTS,EVENTFULLNAME) values (6,'FEEDBACK','COMPLEX',30,'Feedback');
