REM INSERTING into PFINNDISCUSSIONTHREAD_TEMP1
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (459,'How to define the list of collaterals?How to use the data entry screen?',to_timestamp('01-OCT-18 05.40.38.568000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to define the list of collaterals?How to use the data entry screen?',21,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (461,'How to modify repayment schedule?',to_timestamp('01-OCT-18 05.40.58.927000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to modify repayment schedule?',2,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (464,'How to define agency allocation logic?',to_timestamp('01-OCT-18 05.41.35.548000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to define agency allocation logic?',3,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (467,'How to ensure continuity if a team leader leaves the system?How to define agency allocation logic?',to_timestamp('01-OCT-18 05.42.08.687000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to ensure continuity if a team leader leaves the system?How to define agency allocation logic?',3,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (474,'How to handle customer communication?How to modify repayment schedule?',to_timestamp('01-OCT-18 05.43.56.468000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to handle customer communication?How to modify repayment schedule?',7,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (475,'How to handle customer communication?',to_timestamp('01-OCT-18 05.44.05.277000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to handle customer communication?',7,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (485,'How to use the Deep Learning module?',to_timestamp('01-OCT-18 05.47.50.909000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to use the Deep Learning module?',10,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (487,'Market outlook for auto loans in AustraliaMarket outlook for auto loans in India',to_timestamp('01-OCT-18 05.48.12.465000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'CLOSED','Market outlook for auto loans in AustraliaMarket outlook for auto loans in India',12,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (490,'Home loan market in Australia on edge',to_timestamp('01-OCT-18 05.48.46.508000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Home loan market in Australia on edge',14,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (491,'Rise of mortgage insuranceHome loan market in Australia on edge',to_timestamp('01-OCT-18 05.48.59.402000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Rise of mortgage insuranceHome loan market in Australia on edge',14,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (15,'FinnOne CAS Certification Desc,,',to_timestamp('05-OCT-18 09.56.40.675000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','FinnOne CAS Certification',21,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (1054,'Test Thread',to_timestamp('04-JUN-19 03.02.32.725000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Test Thread',2050,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (1055,'Test Thread 1',to_timestamp('04-JUN-19 03.03.23.589000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Test Thread 1',2050,5050);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (1062,'What is a Benami Transaction? Which line of business while financing does it relates to and what is Benami Transactions (Prohibition) Act, 1988?',to_timestamp('10-JUN-19 11.27.47.782000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Benami Transactions',20,5050);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (3051,'How do we measure FinnOne Usage? 1. How many functions of FinnOne module are being used? 2. How many people are logging in on daily basis? 3. has life of end user become simpler or more difficult before and after using the system? If it is 3, how do we measure?',to_timestamp('30-JUL-19 12.43.48.683000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to find FinnOne Neo benefits for user',6,161);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (478,'How to ensure continuity if a team leader leaves the system?',to_timestamp('01-OCT-18 05.44.59.940000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to ensure continuity if a team leader leaves the system?',8,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (481,'How to capture comments on field visit?How to train the field agents to use the mApply?',to_timestamp('01-OCT-18 05.47.13.866000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to capture comments on field visit?How to train the field agents to use the mApply?',9,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (483,'How to create a histogram for variable selection?',to_timestamp('01-OCT-18 05.47.33.475000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to create a histogram for variable selection?',10,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (492,'Rise of mortgage insurance',to_timestamp('01-OCT-18 05.49.16.780000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Rise of mortgage insurance',14,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (3,'Captive Auto Market Trends',to_timestamp('04-OCT-18 10.14.21.118000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Captive Auto Market Trends',18,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (1,'Education Loans Market Trends',to_timestamp('04-OCT-18 10.12.58.409000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Education Loans Market Trends',15,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (2,'Gold Loans Market Trends',to_timestamp('04-OCT-18 10.13.52.756000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Gold Loans Market Trends',16,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (1059,'Co-Origination of loans provides a unique opportunity for Banks and NBFCs to come together to transform their approach in lending to priority sector segment. What all will be the key elements in operationalizing this model, as per the new initiative taken by RBI?',to_timestamp('04-JUN-19 03.27.31.379000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Co-origination of loans by Banks and NBFCs for priority sector lending',20,5050);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (7,'Gold Loans Future Oulooks',to_timestamp('04-OCT-18 10.18.10.642000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Gold Loans Future Oulooks',16,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (3050,'While FinnOne Neo is strong functionally and will keep on growing with each GA release, we need to focus on Operational Efficiency also. Users on ground finally get measured by efficiency and productivity, how FinnOne Neo can help make their daily life simple still needs deep thoughts.',to_timestamp('30-JUL-19 12.36.46.126000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Operational Efficiency',21,161);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (458,'How to use the data entry screen?',to_timestamp('01-OCT-18 05.40.19.243000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to use the data entry screen?',21,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (460,'How to define the list of collaterals?',to_timestamp('01-OCT-18 05.40.47.925000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to define the list of collaterals?',21,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (462,'How to handle customer communication?How to modify repayment schedule?',to_timestamp('01-OCT-18 05.41.08.890000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to handle customer communication?How to modify repayment schedule?',2,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (463,'How to handle customer communication?',to_timestamp('01-OCT-18 05.41.19.711000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to handle customer communication?',2,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (465,'How to ensure continuity if a team leader leaves the system?How to define agency allocation logic?',to_timestamp('01-OCT-18 05.41.42.231000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to ensure continuity if a team leader leaves the system?How to define agency allocation logic?',3,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (466,'How to ensure continuity if a team leader leaves the system?How to define agency allocation logic?',to_timestamp('01-OCT-18 05.41.54.026000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to ensure continuity if a team leader leaves the system?How to define agency allocation logic?',3,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (468,'How to ensure continuity if a team leader leaves the system?',to_timestamp('01-OCT-18 05.42.40.804000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to ensure continuity if a team leader leaves the system?',3,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (469,'Screen Usage, Workflow Discussion',to_timestamp('01-OCT-18 05.43.03.496000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Screen Usage, Workflow Discussion',4,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (470,'How to use the data entry screen?',to_timestamp('01-OCT-18 05.43.18.023000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to use the data entry screen?',6,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (472,'How to define the list of collaterals?',to_timestamp('01-OCT-18 05.43.38.615000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to define the list of collaterals?',6,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (473,'How to modify repayment schedule?',to_timestamp('01-OCT-18 05.43.46.988000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to modify repayment schedule?',7,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (476,'How to define agency allocation logic?',to_timestamp('01-OCT-18 05.44.14.822000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to define agency allocation logic?',8,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (1061,'Why today Banks are happy recovering even half their bad loans than going under the Insolvancy and Bankruptcy Code (IBC) gavel?
',to_timestamp('07-JUN-19 12.08.22.458000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Recent trend in debt recovery by Bank''s.',20,5050);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (480,'How to train the field agents to use the mApply?',to_timestamp('01-OCT-18 05.46.52.448000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to train the field agents to use the mApply?',9,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (1063,'Personal Lease Programme- Latest Trend in Indian Automobile Industry. 

Do you want to drive your Dream car in India, then go for Personal Lease programme.',to_timestamp('17-JUN-19 12.28.12.243000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Personal Lease Programme',6,145);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (502,'Ijarah',to_timestamp('01-OCT-18 05.52.34.970000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Ijarah',19,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (2050,'Aadhaar Data Vault, suggested by UIDAI and RBI, is a mandatory part for any Aadhar number storage and further validation. Now keeping Aadhar number at each system, institutions will keep it in a safe storage and provide a reference key to interfacing system for data fetch. Does it make it safe or still vulnerable to internal systems?',to_timestamp('03-JUL-19 12.04.07.568000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Aadhaar Data Vault',20,221);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (3053,'The Union government on Tuesday announced a scheme for providing a one-time credit guarantee to public sector banks (PSBs) for purchase of pooled non-banking financial companies? (NBFC) assets.
Under the scheme, notified on August 10, public sector banks (PSBs) have been given a deadline of six months to purchase ?pooled assets? of NBFCs at fair value. ?One-time guarantee provided by the government on the pooled assets will be valid for 24 months from the date of purchase and can be invoked on the occurrence of default,? according to the notification.
This follows a Union Budget announcement made by Finance Minister Nirmala Sitharaman that the government will provide a one-time partial credit guarantee to PSBs for first loss of up to 10 per cent for purchase of high-rate pooled assets of NBFCs totaling Rs 1 trillion. The government has laid down ?stringent? criteria for eligibility of NBFCs and housing finance companies (HFCs) to become a part of the scheme and offer their assets for sale to banks. The NBFCs or HFCs should have made a net profit in any of the last two financial years, that is 2017-18 and 2018-19, and their net-performing assets should not be more than 6 per cent till March 31, 2019, the scheme said. 
The government has allowed the NBFCs and HFCs to buy back their assets ?after a specified period of 12 months? as a repurchase transaction, on a right of first refusal basis. 
To begin with, NBFCs will be allowed to sell up to a maximum of 20 per cent of their standard assets as of March 31, 2019 ?subject to a cap of Rs 5,000 crore at fair value?. However, the NBFCs won?t be allowed to sell revolving credit facilities, assets purchased from other entities and assets with ?bullet repayment of both principal and interest? to banks under this scheme. The government will not bear the loss for assets in case they are brought back by the NBFCs or sold by the bank to other entities, the notification stated.
Will this move resolve the liquidity crisis faced by the NBFCs? Please share your thoughts. 
',to_timestamp('20-AUG-19 03.26.54.110000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Banks to get two-year guarantee to purchase ''pooled assets'' of NBFCs. Will this encourage PSBs to buy the pooled assets of NBFCs to combat the liquidity crisis faced currently?',20,261);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (479,'How to ensure continuity if a team leader leaves the system?How to define agency allocation logic?',to_timestamp('01-OCT-18 05.46.38.930000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to ensure continuity if a team leader leaves the system?How to define agency allocation logic?',8,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (486,'Market outlook for auto loans in India',to_timestamp('01-OCT-18 05.48.02.994000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Market outlook for auto loans in India',12,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (8,'Credit Cards Future Oulooks',to_timestamp('04-OCT-18 10.18.27.870000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Credit Cards Future Oulooks',17,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (505,'Istisna',to_timestamp('01-OCT-18 05.53.08.020000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Istisna',19,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (5,'Credit Cards Market Trends',to_timestamp('04-OCT-18 10.16.47.846000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Credit Cards Market Trends',17,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (6,'Education Loans Future Oulooks',to_timestamp('04-OCT-18 10.17.15.530000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Education Loans Future Oulooks',15,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (9,'Captive Auto Future Oulooks',to_timestamp('04-OCT-18 10.18.44.204000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Captive Auto Future Oulooks',18,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (1058,'The Bitcoin reference client uses randomly generated keys. In order to avoid the necessity for a backup after every transaction, (by default) 100 keys are cached in a pool of reserve keys. Still, these wallets are not intended to be shared and used on several systems simultaneously. They support hiding their private keys by using the wallet encrypt feature and not sharing the password, but such "neutered" wallets lose the power to generate public keys as well.

Deterministic wallets do not require such frequent backups, and elliptic curve mathematics permit schemes where one can calculate the public keys without revealing the private keys. This permits for example a webshop business to let its webserver generate fresh addresses (public key hashes) for each order or for each customer, without giving the webserver access to the corresponding private keys (which are required for spending the received funds).

However, deterministic wallets typically consist of a single "chain" of keypairs. The fact that there is only one chain means that sharing a wallet happens on an all-or-nothing basis. However, in some cases one only wants some (public) keys to be shared and recoverable. In the example of a webshop, the webserver does not need access to all public keys of the merchant''s wallet; only to those addresses which are used to receive customer''s payments, and not for example the change addresses that are generated when the merchant spends money. Hierarchical deterministic wallets allow such selective sharing by supporting multiple keypair chains, derived from a single root.',to_timestamp('04-JUN-19 03.24.01.456000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','This document describes hierarchical deterministic wallets (or "HD Wallets"): wallets which can be shared partially or entirely with different systems, each with or without the ability to spend coins.',2050,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (1064,'What is Security Interest? How does it secure a creditor from a default debtor?',to_timestamp('18-JUN-19 10.30.09.564000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Security Interest',20,123);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (471,'How to define the list of collaterals?How to use the data entry screen?',to_timestamp('01-OCT-18 05.43.28.212000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to define the list of collaterals?How to use the data entry screen?',6,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (482,'How to capture comments on field visit?',to_timestamp('01-OCT-18 05.47.22.191000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to capture comments on field visit?',9,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (484,'How to use the Deep Learning module?How to create a histogram for variable selection?',to_timestamp('01-OCT-18 05.47.43.656000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','How to use the Deep Learning module?How to create a histogram for variable selection?',10,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (488,'Market outlook for auto loans in Australia',to_timestamp('01-OCT-18 05.48.25.625000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Market outlook for auto loans in Australia',12,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (489,'Interesting example of personal loan in Europe',to_timestamp('01-OCT-18 05.48.35.595000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Interesting example of personal loan in Europe',13,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (1060,'Should RBI allow old private sector banks to be merged with NBFC''s. What do you think about this. Share your valuable views.

For more information visit below site:
https://economictimes.indiatimes.com/industry/banking/finance/banking/nbfcs-and-old-private-sector-banks-made-for-each-other/articleshow/69551489.cms',to_timestamp('07-JUN-19 09.06.02.337000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Should RBI allow old private sector banks to be merged with NBFC''s. What do you think about this.',20,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (3052,'With a slump in the auto industry, and industry leaders have warned of massive job cuts as manufacturers look to halt production. How will this affect the auto loan business',to_timestamp('14-AUG-19 10.36.07.173000000 AM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Auto sector crisis: 2.30 lakh jobs lost as industry faces worst crisis in 20 years',12,141);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (506,'IFRS 9',to_timestamp('01-OCT-18 05.53.20.873000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','IFRS 9',20,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (503,'Murabaha',to_timestamp('01-OCT-18 05.52.48.722000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Murabaha',19,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (504,'Tawarruq',to_timestamp('01-OCT-18 05.52.59.514000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','Tawarruq',19,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (507,'GDPR',to_timestamp('01-OCT-18 05.53.29.291000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'OPEN','GDPR',20,2);
Insert into PFINNDISCUSSIONTHREAD_TEMP1 (DISCUSSIONTHREADID,DESCRIPTION,POSTEDDATE,THREADSTATUS,TITLE,CATEGORY_CATEGORYID,POSTEDBYUSER_USERID) values (397,'New thread',to_timestamp('22-OCT-18 05.49.37.992000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'CLOSED','New Thread 123',2,2);
