REM INSERTING into PFINNBADGEMASTER
Insert into PFINNBADGEMASTER (BADGENAME,MAXPOINT,MINPOINT) values ('BRONZE',0,100);
Insert into PFINNBADGEMASTER (BADGENAME,MAXPOINT,MINPOINT) values ('SILVER',101,200);
Insert into PFINNBADGEMASTER (BADGENAME,MAXPOINT,MINPOINT) values ('GOLD',201,300);
Insert into PFINNBADGEMASTER (BADGENAME,MAXPOINT,MINPOINT) values ('PLATINUM',301,100000);
