REM INSERTING into table_export
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (399,'ICICI has advertized pre authorized auto loans to be disbursed within 4 hours during the festive season.',to_timestamp('23-OCT-18 09.28.04.827000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('23-OCT-18 09.30.45.625000000 AM','DD-MON-RR HH.MI.SS.FF AM'),9,1,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (3050,'First Post sub',to_timestamp('27-FEB-19 04.47.20.576000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('27-FEB-19 04.47.19.926000000 PM','DD-MON-RR HH.MI.SS.FF AM'),15,2,162);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (4051,'What does the Sarfaesi Act cover?',to_timestamp('10-JUN-19 02.44.52.577000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'sunita approved ','APPROVED',to_timestamp('11-JUN-19 01.18.50.285000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1061,5052,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (4052,'What does the Sarfaesi Act cover?',to_timestamp('10-JUN-19 02.44.54.703000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'DELETED',to_timestamp('17-JUN-19 12.07.06.159000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1061,5052,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (4053,'What does the Sarfaesi Act cover?',to_timestamp('10-JUN-19 02.44.58.110000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'REJECTED',to_timestamp('17-JUN-19 12.21.28.343000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1061,5052,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (5053,'One of the recent events(not trend) in Education loan market in India has been the creation of Vidya Lakshmi Portal. Vidya Lakshmi is a first of its kind portal for students seeking Education Loan. This portal has been developed under the guidance of Department of Financial Services, (Ministry of Finance) , Department of Higher Education (Ministry of Human Resource Development) and Indian Banks Association (IBA).The portal has been developed and being maintained by NSDL e-governance LTD. Students can view, apply and track the education loan applications to banks anytime, anywhere by accessing the portal. The portal also provides linkages to National Scholarship Portal. It has the following features:

Information about Educational Loan Schemes of Banks
Common Educational Loan Application Form for Students
Apply to multiple Banks for Educational Loans
Facility for Banks to download Students Loan Applications
Facility for Banks to upload loan processing status
Facility for Students to email grievances/queries relating to Educational Loans to Banks
Linkage to National Scholarship Portal for information and application for Govt Scholarships',to_timestamp('26-JUN-19 07.50.29.038000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('02-JUL-19 11.12.16.173000000 AM','DD-MON-RR HH.MI.SS.FF AM'),1,5058,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (5055,'Vidya Lakshmi is a first of its kind portal for students seeking Education Loan. This portal has been developed under the guidance of Department of Financial Services, (Ministry of Finance) , Department of Higher Education (Ministry of Human Resource Development) and Indian Banks Association (IBA).The portal has been developed and being maintained by NSDL E-governance ltd. It has following features-
1) Information about Educational Loan Schemes of Banks
2) Common Educational Loan Application Form for Students
3) Apply to multiple Banks for Educational Loans
4) Facility for Banks to download Students Loan Applications
5) Facility for Banks to upload loan processing status
6) Facility for Students to email grievances/queries relating to Educational Loans to Banks
7) Linkage to National Scholarship Portal for information and application for Govt Scholarships
',to_timestamp('26-JUN-19 07.55.10.327000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('26-JUN-19 07.55.10.264000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,181,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (5058,'Bad Loans Fall To 9.3% In 2018-19: RBI Report
The share of the state-run banks in the overall NPAs was at an elevated 12.6 per cent, but is likely to come down to 12 per cent by March 2020',to_timestamp('28-JUN-19 01.56.42.015000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('02-JUL-19 11.12.16.173000000 AM','DD-MON-RR HH.MI.SS.FF AM'),1061,5052,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (5059,'Murabaha is an islamic financing product under which bank sells the asset to customer at the cost price + Markup. Markup is the profit of bank. In Murabaha bank and buyer of asset formulate a contract of sale. In a murabaha contract of sale, the client petitions the bank to purchase an item for him/her. Complying with the client''s request, the bank establishes a contract setting the cost and profit for the item, with repayment typically in installments. Because a profit markup is charged rather than interest(Riba), this form of financing is legal in Islamic Finance. It is to be noted that In Islam charging interest is considered Haram(illegal as per Islamic Faith).',to_timestamp('28-JUN-19 06.26.31.843000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('28-JUN-19 06.26.31.743000000 PM','DD-MON-RR HH.MI.SS.FF AM'),503,181,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (6050,'Want to know more details about Islamic Finance.',to_timestamp('29-JUL-19 08.18.15.013000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'ok','APPROVED',to_timestamp('02-AUG-19 04.26.16.019000000 PM','DD-MON-RR HH.MI.SS.FF AM'),503,12053,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (6052,'We first need to understand pain point of end users. It can only be achieved using direct talk and on floor visit. It gives us real insight of how users use the system. we have seen couple of places that users are not aware of available system functions which can ease their life. We did similar exercise with ICICI bank and found that their call center user mange three systems to reply to online query of customer and often face logout issue. we created a separate system for them which has reduced their time by 70%. Neo customer service is replica of that which is going to change customer service users life. Like wise, we found that LPP calculation takes lot of time of users and proposed to product for LPP breakup which is available in Neo now. It will reduce around 60-80% time of end user as per current feedback.',to_timestamp('02-AUG-19 03.54.40.035000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'ok','APPROVED',to_timestamp('02-AUG-19 04.26.16.019000000 PM','DD-MON-RR HH.MI.SS.FF AM'),3051,10051,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (6053,'Could you pls. marketing person to share with others. They can upload on this portal or share path on this discussion. ',to_timestamp('02-AUG-19 04.33.52.183000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('02-AUG-19 04.33.52.089000000 PM','DD-MON-RR HH.MI.SS.FF AM'),3050,221,6051);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (6055,'This is absolutely perfect, it explains how Neo benefited from previous state. But I am thinking how to measure FinnOne usage by extracting information from FinnOne Neo without involving customer. Objective is to measure how much % of the functionality available to business is used by them. Whatever is unused, we can then discuss and understand why it is not been used - whether it is due to business rules not being relevant or any other reason. Lots of time, customer actually may not be knowing each and every function of the system that is available off the shelf.',to_timestamp('13-AUG-19 03.04.50.766000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'ok','APPROVED',to_timestamp('13-AUG-19 03.06.46.124000000 PM','DD-MON-RR HH.MI.SS.FF AM'),3051,5057,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (162,'First Post',to_timestamp('18-OCT-18 11.46.33.818000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'DELETED',to_timestamp('27-FEB-19 04.49.38.005000000 PM','DD-MON-RR HH.MI.SS.FF AM'),15,2,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (402,'ICICI has advertized pre authorized auto loans to be disbursed within 4 hours during the festive season.',to_timestamp('23-OCT-18 09.47.26.782000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('28-NOV-18 09.53.54.972000000 AM','DD-MON-RR HH.MI.SS.FF AM'),9,1,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (4050,'There are below two main reasons due to which Banks readily accept recovery of even half of their bad loans - 

(1) Sarfaesi, the original bad-loan resolution mechanism, didn?t work because of painful, lengthy processes
.
(2) The new insolvency law, too, suffers from similar problems, forcing banks to settle cases outside its ambit

Then what should Government do to resolve above two? ',to_timestamp('10-JUN-19 08.55.25.152000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('10-JUN-19 08.55.24.824000000 AM','DD-MON-RR HH.MI.SS.FF AM'),1061,5050,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (4058,'This is what is going to be a big trend in India. Typically under personal lease programme a consumer can pay 20% down-payment of a vehicle and drive it home, paying monthly rentals. But today, thanks to personal lease programme from automakers such as Hyundai, Mahindra, Skoda and Fiat, the consumers can now drive home their dream car without making a down payment, enjoy hassle-free maintenance services and upgrade to a new product of their choice.',to_timestamp('18-JUN-19 08.18.17.654000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('18-JUN-19 08.19.18.608000000 AM','DD-MON-RR HH.MI.SS.FF AM'),1063,5050,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (5056,'Alok San, What are those circumstances, In retail lending i have not come across any such scenarios. Typically person providing collateral is taken as a co-applicant in the loan. Can you please elaborate on this.',to_timestamp('26-JUN-19 08.06.29.892000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('26-JUN-19 08.06.29.808000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1064,181,5052);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (6054,'I am talking about efficiency of Operations people who are working on high volumes of applications. I observed at a customer site on operations floor, how they are spending about 20 minutes to punch an application at DDE. 1. Lots of fields that had one value in master (default value) had to be chosen by each click to move forward (could be default value, so that there is no need to click) 2. Avoid scrolling across multiple tabs, kind of collapsing.
Objective is think options on how to make data entry possible in 5 minutes maximum - minimum use of mouse and number of clicks.
For verification stage, customer had made separate application (outside FinnOne Neo) to validate the data as it matches their application form, thereby reducing checking time drastically. FInnOne Neo screen not used to do the same, because of efficiency.',to_timestamp('13-AUG-19 11.48.28.962000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('13-AUG-19 03.07.02.769000000 PM','DD-MON-RR HH.MI.SS.FF AM'),3050,5057,6051);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (2050,'Second Post',to_timestamp('10-DEC-18 03.57.53.625000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'DELETED',to_timestamp('27-FEB-19 04.46.49.634000000 PM','DD-MON-RR HH.MI.SS.FF AM'),15,2,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (4054,'Indian financial markets woke up to fresh worries earlier last week after DHFL missed its coupon repayments on bonds and Fitch downgraded ICICI Bank and Axis Bank. While the DHFL episode once again exposed the vulnerabilities in the debt mutual-fund space, the downgrade, triggered by the weak operating environment that India?s lenders are facing, had a chilling message. 

The National Company Law Tribunals (NCLT) were expected to replace Debt Recovery Tribunals (DRT) which were plagued by legal delays and piling of cases. In the current form, the debt tribunals are nothing but another layer in the recovery mechanism. As things stand, the IBC seem to be heading the Sarfaesi way.

Hence, to resolve the issues discussed in earlier threads, the government must live up to its promise of setting up fast-track and commercial courts for expeditious disposal of cases.',to_timestamp('11-JUN-19 08.53.25.623000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('11-JUN-19 08.53.25.292000000 AM','DD-MON-RR HH.MI.SS.FF AM'),1061,5050,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (4055,'Benami is a South Asian word that means "without name" or "no name". In this Act, the word is used to define a transaction in which the real beneficiary is not the one in whose name the property is purchased. As a result, the person in whose name the property is purchased is just a mask of the real beneficiary.
Benami Transactions (Prohibition) Act, 1988 is an Act of the Parliament of India that prohibits certain types of financial transactions. The act defines a ''benami'' transaction as any transaction in which property is transferred to one person for consideration paid by another person. Such transactions were a feature of the Indian economy, usually relating to the purchase of property (real estate), and were thought to contribute to the Indian black money problem. The act bans all benami transactions and gives the government the right to recover property held benami without paying any compensation. The act came into force on 5 September 1988. Although benami transactions are now illegal, the act had limited success in curbing them.
WHAT UPDATE WERE MADE IN THE ACT TO CURB AND ENFORCE MORE STRINGENT RULES TO ENFORCE THE PROHIBITIONS?',to_timestamp('17-JUN-19 10.40.50.501000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('17-JUN-19 12.05.13.783000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1062,5050,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (4059,'What are the checks and conditions for personal lease program - and how long does the process take',to_timestamp('18-JUN-19 08.52.38.475000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('18-JUN-19 08.52.38.114000000 AM','DD-MON-RR HH.MI.SS.FF AM'),1063,2,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (5057,'1. A customer reaches out to you when they are unsure, confused or have a grievance. He may, sometimes, be angry because of miscommunication or because he feels that he has been treated unfairly. Many-a-times, a great deal of patience is required just to understand the problem, let alone offer a solution
2.  It is the responsibility of management to ensure that staff is communicated accurate turnaround times, which can be used to set the customers? expectations.
3. When you have a customer waiting for your response, be proactive and keep the customer informed of the progress rather than have the customer get in touch with you time and again for an update
4. While attending to a customer complaint, if you happen to miss out any important details, it would just aggravate the situation. Attentiveness helps',to_timestamp('28-JUN-19 01.54.33.662000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('02-JUL-19 11.12.16.173000000 AM','DD-MON-RR HH.MI.SS.FF AM'),475,5052,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (6051,'Great point, infact we are glad to share their ease of usage, driving operational efficiency, and enabling faster go to market with new tailored products and features are the key themes that we keep as focus in every GA roadmap. Marketing team has released a recent article on how FinnOne Neo 4.0 boosts Operational Efficiency for our customers. ',to_timestamp('30-JUL-19 03.07.24.070000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'ok','APPROVED',to_timestamp('02-AUG-19 04.26.16.019000000 PM','DD-MON-RR HH.MI.SS.FF AM'),3050,5061,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (396,'test',to_timestamp('22-OCT-18 05.44.28.462000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('22-OCT-18 05.45.03.618000000 PM','DD-MON-RR HH.MI.SS.FF AM'),9,1,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (100,'Good Product',to_timestamp('03-DEC-18 06.31.43.796000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('03-DEC-18 06.31.43.709000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,2,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (5050,'Some credit card experts say 2019 might usher in a more austere period for credit card rewards, especially if interest rates continue to rise and the economy struggles.',to_timestamp('25-JUN-19 08.43.50.627000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('25-JUN-19 08.43.50.545000000 AM','DD-MON-RR HH.MI.SS.FF AM'),5,141,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (5054,'Vidya Lakshmi Portal is a new trend in Education loan Market in india',to_timestamp('26-JUN-19 07.52.51.185000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('26-JUN-19 07.52.51.107000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1,181,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (400,'veryinteresting',to_timestamp('23-OCT-18 09.31.47.488000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'REJECTED',to_timestamp('18-JUN-19 10.33.29.161000000 AM','DD-MON-RR HH.MI.SS.FF AM'),9,1,399);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (401,'ICICI has advertized pre authorized auto loans to be disbursed within 4 hours during the festive season.',to_timestamp('23-OCT-18 09.46.49.851000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('23-OCT-18 09.46.49.784000000 AM','DD-MON-RR HH.MI.SS.FF AM'),9,2,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (50,'Does any one have knowledge about this?',to_timestamp('03-DEC-18 12.49.35.057000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('03-DEC-18 12.49.34.963000000 PM','DD-MON-RR HH.MI.SS.FF AM'),472,2,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (4056,'Covered in another discussion thread specifically opened for Sarfaesi',to_timestamp('17-JUN-19 12.08.59.748000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'DELETED',to_timestamp('17-JUN-19 12.10.19.125000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1061,123,4051);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (4057,'SARFAESI Act : The Securitisation and Reconstruction of Financial Assets and Enforcement of Securities Interest Act, 2002 (also known as the SARFAESI Act) is an Indian law. It allows banks and other financial institution to auction residential or commercial properties to recover loans. It regulate securitization and reconstruction of financial assets and enforcement of security interest and to provide for a central database of security interests created on property rights and for matters connected therewith or incidental thereto. The SARFAESI Act deals with Securitization, Asset reconstruction, Enforcement of security without intervention of the court. The whole procedure is regulated by the RBI. 

The SARFAESI Act allows secured creditors to take possession over collateral against which a loan had been provided upon a default in repayment. This process is undertaken with assistance of the District Magistrate, and does not require the intervention of courts or tribunals. This Act helps the Banks and Financial Institutions who are the secured creditors to enforce securities held as collaterals to loans disbursed by them, if such loans turn to be Non Performing Assets.
Under SARFAESI Act, secured creditors which include Banks and Financial institution can refer the Non-Performing Asset (?NPA?) to any Asset Reconstruction Company, established with the Reserve Bank of India under section 3 for the purposes of the Asset Reconstruction or Securitization or both.
The provisions of this Act are applicable only for NPA loans with outstanding above Rs. 1,00,000/- (Rupees One Lakh). NPA loan accounts where the amount is less than 20% of the principal and interest are not eligible to be dealt with under this Act. NPA should be backed by Securities charged to the bank by way of hypothecation or charge or assignment.',to_timestamp('17-JUN-19 12.20.46.088000000 PM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('17-JUN-19 12.21.28.343000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1061,5050,4051);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (4060,'HDFC is offering Gold loan disbursal in 45 minutes with unique layered security, one page documentation and special rates for women. ',to_timestamp('18-JUN-19 08.59.47.552000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('18-JUN-19 10.33.13.287000000 AM','DD-MON-RR HH.MI.SS.FF AM'),2,5052,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (4061,'A security interest is a legal right granted by a debtor to a creditor over the debtor''s property (usually a collateral) which enables the creditor to have recourse to the property if the debtor defaults in making payment or otherwise performing the secured obligations. One of the most common examples of a security interest is a mortgage.
When mortgagee, pledges by a promise to pay a certain sum of money, with certain conditions, on a said date or dates for a said period, that action on the page with wet ink applied on the part of the one wishing the exchange, creates the original funds and negotiable Instrument. That action of pledging conveys a promise binding upon the mortgagee which creates a face value upon the Instrument of the amount of currency being asked for in exchange. It is therein in good faith offered to the Bank in exchange for local currency from the Bank to buy a house. This creates a security interest in the land the house sits on for the Bank and they file a caveat at land titles on the house as evidence of that security interest. If the mortgagee fails to pay, defaulting in his promise to repay the exchange, the bank then applies to the court to for-close on your property to eventually sell the house and apply the proceeds to the outstanding exchange.',to_timestamp('19-JUN-19 08.56.44.689000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('19-JUN-19 08.57.17.785000000 AM','DD-MON-RR HH.MI.SS.FF AM'),1064,5050,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (4062,'Is it also possible for a person to grant security over their property as collateral for the debts of another person',to_timestamp('19-JUN-19 09.16.04.938000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('20-JUN-19 12.34.31.736000000 PM','DD-MON-RR HH.MI.SS.FF AM'),1064,5052,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (5051,'Five credit card trends to look for in 2019:

1. More dining and entertainment rewards
2. More co-branded retail cards
3. More credit card spending
4. More contactless options
5. Higher interest rates',to_timestamp('25-JUN-19 08.46.00.134000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('25-JUN-19 08.49.18.234000000 AM','DD-MON-RR HH.MI.SS.FF AM'),5,5052,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (5052,'Yes, in certain circumstances a person can grant security over their property, as a collateral for the debts of another person. Such kind of security is called third party security.',to_timestamp('25-JUN-19 08.48.02.852000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,'APPROVED',to_timestamp('25-JUN-19 08.48.48.185000000 AM','DD-MON-RR HH.MI.SS.FF AM'),1064,5050,null);
Insert into "table_export" (DISCUSSIONPOSTID,POSTCONTENT,POSTEDDATE,REMARKFORSTATUS,STATUS,STATUSTIME,"DISCUSSIONTHREAD_DISCUSSIONTHREADID",POSTEDBYUSER_USERID,"QUOTEDDISCUSSIONPOST_DISCUSSIONPOSTID") values (5060,'I read somwehere that In a murabaha contract of sale, the client petitions the bank to purchase an item for him/her. ... In a murabaha contract for sale, the bank buys an asset and then sells the asset back to the client with a profit charge. This type of transaction is halal or valid, according to Islamic Sharia/Shar&#299;&#703;ah.',to_timestamp('02-JUL-19 02.26.20.836000000 PM','DD-MON-RR HH.MI.SS.FF AM'),'valid information','APPROVED',to_timestamp('03-JUL-19 12.05.36.403000000 AM','DD-MON-RR HH.MI.SS.FF AM'),503,5052,null);
