REM INSERTING into PORTALQUIZCHECK
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (2100,'class',357,'manishjindal');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (2101,'50',38,'manishjindal');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (2102,'0 to 65535',356,'manishjindal');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (2103,'JVM',388,'manishjindal');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (2104,'Process restart',389,'manishjindal');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (3108,'All of the above.',43,'prateek.sharma1');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (3109,'All of the above.',48,'prateek.sharma1');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (3110,'extended business operations during routine processing cycle.',39,'prateek.sharma1');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (3111,'both a and c',40,'prateek.sharma1');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (50,'Box obj = new Box();',358,'user');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (51,'0 to 65535',356,'user');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (52,'class',357,'user');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (53,'JVM',388,'user');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (54,'Process restart',389,'user');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (1104,'All of the above.',48,'sunita.mittal');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (1105,'All of the above.',43,'sunita.mittal');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (1106,'both a and c',40,'sunita.mittal');
Insert into PORTALQUIZCHECK (QUIZCHECKID,CORRECTANSWER,QUIZQUESTIONID,USERNAME) values (1107,'extended business operations during routine processing cycle.',39,'sunita.mittal');
